import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:provider/provider.dart';
import 'package:uuid/uuid.dart';
import '../../core/providers/app_provider.dart';
import '../../core/theme/app_typography.dart';
import '../../models/task.dart';
import '../../shared/widgets/app_button.dart';
import '../../shared/widgets/app_card.dart';
import '../../shared/widgets/app_input.dart';
import '../../shared/widgets/tutorial_banner.dart';
import '../../app.dart';

/// Visual Lua Boolean Expression Builder.
/// Supports simple boolean expressions: AND, OR, NOT, comparisons.
class LuaBuilderPage extends StatefulWidget {
  const LuaBuilderPage({super.key});

  @override
  State<LuaBuilderPage> createState() => _LuaBuilderPageState();
}

class _LuaBuilderPageState extends State<LuaBuilderPage> {
  final _ExpressionNode _root = _GroupNode(op: 'and');

  String to_lua(_ExpressionNode node) {
    if (node is _ConditionNode) {
      if (node.left.isEmpty) return 'true';
      final val = node.quoted ? '"${node.right}"' : node.right;
      final expr = '${node.left} ${node.op} $val';
      return node.negated ? 'not ($expr)' : expr;
    } else if (node is _GroupNode) {
      if (node.children.isEmpty) return 'true';
      final parts = node.children.map((c) => to_lua(c)).toList();
      if (parts.length == 1) {
        return node.negated ? 'not (${parts.first})' : parts.first;
      }
      final joined = parts.join(' ${node.op} ');
      return node.negated ? 'not ($joined)' : '($joined)';
    }
    return 'true';
  }

  void show_save_as_task_dialog(BuildContext context) {
    final nameController = TextEditingController(text: 'Lua Expression');
    showDialog<void>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: Text(ctx.l10n.saveLuaTaskTitle),
        content: SizedBox(
          width: 360,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                ctx.l10n.saveLuaTaskMessage,
                style: Theme.of(ctx).textTheme.bodySmall?.copyWith(
                    color: Theme.of(ctx)
                        .colorScheme
                        .onSurface
                        .withOpacity(0.6)),
              ),
              const SizedBox(height: 16),
              AppInput(
                label: ctx.l10n.luaTaskNameLabel,
                hint: ctx.l10n.luaTaskNameHint,
                controller: nameController,
              ),
            ],
          ),
        ),
        actions: [
          AppButton(
            label: ctx.l10n.cancelButton,
            variant: AppButtonVariant.ghost,
            onPressed: () => Navigator.of(ctx).pop(),
          ),
          AppButton(
            label: ctx.l10n.createTaskButton,
            icon: const Icon(Icons.add_task),
            onPressed: () {
              final name = nameController.text.trim();
              if (name.isEmpty) return;
              final luaScript =
                  '-- FuzzyBoard Lua Expression\n-- Auto-generated by Lua Builder\n\nlocal function evaluate(ctx)\n  return ${to_lua(_root)}\nend';
              final task = Task(
                id: const Uuid().v4(),
                name: name,
                description: luaScript,
                priority: TaskPriority.medium,
                tags: ['lua', 'expression'],
                config: {
                  'source': 'lua_builder',
                },
              );
              context.read<AppProvider>().addTask(task);
              Navigator.of(ctx).pop();
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(
                  content: Text(context.l10n.taskCreatedSnackbar(name)),
                  action: SnackBarAction(
                    label: context.l10n.viewTasksAction,
                    onPressed: () => Navigator.of(context).pop(),
                  ),
                ),
              );
            },
          ),
        ],
      ),
    ).then((_) => nameController.dispose());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(context.l10n.luaExpressionBuilderTitle),
        actions: [
          AppButton(
            label: context.l10n.luaCopyButton,
            icon: const Icon(Icons.copy),
            size: AppButtonSize.sm,
            variant: AppButtonVariant.outline,
            onPressed: () async {
              await Clipboard.setData(ClipboardData(text: to_lua(_root)));
              if (context.mounted) {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(content: Text(context.l10n.luaCopiedSnackbar)),
                );
              }
            },
          ),
          const SizedBox(width: 8),
          AppButton(
            label: context.l10n.luaSaveAsTask,
            icon: const Icon(Icons.add_task),
            size: AppButtonSize.sm,
            onPressed: () => show_save_as_task_dialog(context),
          ),
          const SizedBox(width: 12),
        ],
      ),
      body: LayoutBuilder(
        builder: (context, constraints) {
          final wide = constraints.maxWidth > 700;
          return wide
              ? Row(
                  children: [
                    Expanded(
                      flex: 3,
                      child: Column(
                        children: [
                          TutorialBanner(
                            title: context.l10n.luaExpressionBuilderTitle,
                            emoji: '🌙',
                            steps: const [
                              'Use AND/OR groups to combine multiple conditions. Click "Add Condition" to start.',
                              'Each condition has a left-hand variable, an operator (==, ~=, >, < …), and a right-hand value.',
                              'Toggle NOT to negate any condition or group.',
                              'Enable "str" to quote the right-hand value as a Lua string.',
                              'Click "Add Group" to nest conditions. The Lua Code panel updates live.',
                              'Hit "Save as Task" to convert the expression into a Task with the full script.',
                            ],
                          ),
                          Expanded(child: build_builder()),
                        ],
                      ),
                    ),
                    VerticalDivider(
                        width: 1,
                        color: Theme.of(context)
                            .colorScheme
                            .outline
                            .withOpacity(0.2)),
                    Expanded(flex: 2, child: build_output()),
                  ],
                )
              : DefaultTabController(
                  length: 2,
                  child: Column(
                    children: [
                      TutorialBanner(
                        title: context.l10n.luaExpressionBuilderTitle,
                        emoji: '🌙',
                        steps: const [
                          'Add conditions inside AND/OR groups. Toggle NOT to negate.',
                          'The Lua Code tab shows the live-generated script.',
                          'Use "Save as Task" to create a task from this expression.',
                        ],
                      ),
                      TabBar(tabs: [
                        Tab(text: context.l10n.luaTabBuilder),
                        Tab(text: context.l10n.luaTabCode),
                      ]),
                      Expanded(
                        child: TabBarView(children: [
                          build_builder(),
                          build_output(),
                        ]),
                      ),
                    ],
                  ),
                );
        },
      ),
    );
  }

  Widget build_builder() {
    return ListView(
      padding: const EdgeInsets.all(16),
      children: [
        // Header
        AppCard(
          title: '🌙 Lua Expression Builder',
          subtitle: context.l10n.luaSubtitle,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                context.l10n.luaDescription,
                style: Theme.of(context).textTheme.bodySmall?.copyWith(
                    color: Theme.of(context)
                        .colorScheme
                        .onSurface
                        .withOpacity(0.6)),
              ),
            ],
          ),
        ).animate().fadeIn(),
        const SizedBox(height: 16),
        // Root group
        build_group_node(_root as _GroupNode, isRoot: true),
      ],
    );
  }

  Widget build_group_node(_GroupNode group, {bool isRoot = false}) {
    final cs = Theme.of(context).colorScheme;
    final groupColor =
        group.op == 'and' ? const Color(0xFF3B82F6) : const Color(0xFF8B5CF6);

    return Container(
      // Add this — forces the container (and its Row children) to
      // fill the available width rather than size to content
      width: double.infinity,
      decoration: BoxDecoration(
        border: Border(
          left: BorderSide(color: groupColor, width: 3),
        ),
      ),
      margin: const EdgeInsets.only(left: 4),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(12, 8, 8, 8),
            child: Row(
              children: [
                ToggleButtons(
                  isSelected: [group.op == 'and', group.op == 'or'],
                  onPressed: (i) =>
                      setState(() => group.op = i == 0 ? 'and' : 'or'),
                  borderRadius: BorderRadius.circular(8),
                  constraints:
                      const BoxConstraints(minWidth: 48, minHeight: 32),
                  children: const [
                    Text('AND',
                        style: TextStyle(
                            fontSize: 12, fontWeight: FontWeight.w600)),
                    Text('OR',
                        style: TextStyle(
                            fontSize: 12, fontWeight: FontWeight.w600)),
                  ],
                ),
                const SizedBox(width: 8),
                _SmallToggle(
                    label: 'NOT',
                    active: group.negated,
                    onTap: () =>
                        setState(() => group.negated = !group.negated)),
                const Spacer(),
                AppButton(
                  label: 'Add Condition',
                  icon: const Icon(Icons.add),
                  size: AppButtonSize.sm,
                  variant: AppButtonVariant.outline,
                  onPressed: () => setState(() {
                    group.children.add(_ConditionNode());
                  }),
                ),
                const SizedBox(width: 6),
                AppButton(
                  label: 'Add Group',
                  icon: const Icon(Icons.account_tree_outlined),
                  size: AppButtonSize.sm,
                  variant: AppButtonVariant.ghost,
                  onPressed: () => setState(() {
                    group.children.add(_GroupNode(op: 'and'));
                  }),
                ),
                if (!isRoot) ...[
                  const SizedBox(width: 6),
                  IconButton(
                    icon: Icon(Icons.close,
                        size: 16, color: cs.onSurface.withOpacity(0.4)),
                    visualDensity: VisualDensity.compact,
                    onPressed: () => setState(() {
                      remove_from_tree(_root as _GroupNode, group);
                    }),
                  ),
                ],
              ],
            ),
          ),
          Padding(
            padding: const EdgeInsets.only(left: 16),
            child: Column(
              // Add this too — same issue would occur in nested columns
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: group.children.asMap().entries.map((e) {
                final child = e.value;
                return Padding(
                  padding: const EdgeInsets.only(bottom: 8),
                  child: child is _GroupNode
                      ? build_group_node(child)
                      : build_condition_node(child as _ConditionNode, group),
                );
              }).toList(),
            ),
          ),
        ],
      ),
    );
  }

  Widget build_condition_node(_ConditionNode node, _GroupNode parent) {
    return _ConditionRow(node: node, parent: parent, onChanged: () => setState(() {}));
  }

  void remove_from_tree(_GroupNode group, _GroupNode target) {
    group.children.removeWhere((c) => c == target);
    for (final child in group.children) {
      if (child is _GroupNode) {
        remove_from_tree(child, target);
      }
    }
  }

  Widget build_output() {
    final isDark = Theme.of(context).colorScheme.brightness == Brightness.dark;
    final lua = to_lua(_root);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.fromLTRB(16, 16, 16, 8),
          child: Row(
            children: [
              Text(context.l10n.luaGeneratedCode,
                  style: Theme.of(context).textTheme.titleSmall),
              const Spacer(),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                decoration: BoxDecoration(
                  color: const Color(0xFF8B5CF6).withOpacity(0.12),
                  borderRadius: BorderRadius.circular(6),
                ),
                child: Text(context.l10n.luaLiveBadge,
                    style: const TextStyle(
                        fontSize: 10,
                        color: Color(0xFF8B5CF6),
                        fontWeight: FontWeight.w700)),
              ),
            ],
          ),
        ),
        // Full script template
        Expanded(
          child: Container(
            margin: const EdgeInsets.all(16),
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: isDark ? const Color(0xFF0D0D1A) : const Color(0xFFF5F5FF),
              borderRadius: BorderRadius.circular(12),
            ),
            child: SelectableText(
              '-- FuzzyBoard Lua Expression\n-- Auto-generated by Lua Builder\n\nlocal function evaluate(ctx)\n  return $lua\nend\n\n-- Example usage:\n-- local result = evaluate({\n--   status = "active",\n--   count = 5,\n-- })',
              style: AppTypography.mono.copyWith(
                color: const Color(0xFF8B5CF6),
                fontSize: 13,
              ),
            ),
          ),
        ),
        // Cheat sheet
        Padding(
          padding: const EdgeInsets.all(16),
          child: AppCard(
            title: '📖 Lua Cheatsheet',
            child: _LuaCheatsheet(),
          ),
        ),
      ],
    );
  }
}

class _LuaCheatsheet extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final rows = [
      ('==', 'Equal'),
      ('~=', 'Not equal'),
      ('>', 'Greater than'),
      ('<', 'Less than'),
      ('and', 'Logical AND'),
      ('or', 'Logical OR'),
      ('not', 'Logical NOT'),
    ];

    return Wrap(
      spacing: 12,
      runSpacing: 6,
      children: rows.map((r) {
        return Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
              decoration: BoxDecoration(
                color: const Color(0xFF8B5CF6).withOpacity(0.1),
                borderRadius: BorderRadius.circular(5),
              ),
              child: Text(r.$1,
                  style: AppTypography.mono
                      .copyWith(fontSize: 11, color: const Color(0xFF8B5CF6))),
            ),
            const SizedBox(width: 4),
            Text(r.$2, style: theme.textTheme.bodySmall),
          ],
        );
      }).toList(),
    );
  }
}

class _SmallToggle extends StatelessWidget {
  final String label;
  final bool active;
  final VoidCallback onTap;

  const _SmallToggle(
      {required this.label, required this.active, required this.onTap});

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    return GestureDetector(
      onTap: onTap,
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 150),
        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
        decoration: BoxDecoration(
          color: active
              ? cs.primary.withOpacity(0.2)
              : cs.onSurface.withOpacity(0.06),
          borderRadius: BorderRadius.circular(6),
        ),
        child: Text(
          label,
          style: TextStyle(
            fontSize: 11,
            fontWeight: FontWeight.w600,
            color: active ? cs.primary : cs.onSurface.withOpacity(0.5),
          ),
        ),
      ),
    );
  }
}

// ── Condition Row ─────────────────────────────────────────────────────────────

class _ConditionRow extends StatefulWidget {
  final _ConditionNode node;
  final _GroupNode parent;
  final VoidCallback onChanged;

  const _ConditionRow({
    required this.node,
    required this.parent,
    required this.onChanged,
  });

  @override
  State<_ConditionRow> createState() => _ConditionRowState();
}

class _ConditionRowState extends State<_ConditionRow> {
  late TextEditingController leftController;
  late TextEditingController rightController;

  @override
  void initState() {
    super.initState();
    leftController = TextEditingController(text: widget.node.left);
    rightController = TextEditingController(text: widget.node.right);
  }

  @override
  void dispose() {
    leftController.dispose();
    rightController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    const ops = ['==', '~=', '>', '<', '>=', '<='];
    final cs = Theme.of(context).colorScheme;

    return Container(
      padding: const EdgeInsets.all(10),
      decoration: BoxDecoration(
        color: cs.surface,
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: cs.outline.withOpacity(0.2)),
      ),
      child: Row(
        children: [
          _SmallToggle(
            label: 'NOT',
            active: widget.node.negated,
            onTap: () {
              widget.node.negated = !widget.node.negated;
              widget.onChanged();
            },
          ),
          const SizedBox(width: 8),
          Expanded(
            child: TextField(
              decoration: InputDecoration(
                hintText: 'variable',
                contentPadding: const EdgeInsets.symmetric(horizontal: 10, vertical: 8),
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(8), borderSide: BorderSide.none),
                filled: true,
              ),
              controller: leftController,
              onChanged: (v) {
                widget.node.left = v;
                widget.onChanged();
              },
              style: AppTypography.mono.copyWith(fontSize: 12),
            ),
          ),
          const SizedBox(width: 6),
          SizedBox(
            width: 70,
            child: DropdownButtonHideUnderline(
              child: DropdownButton<String>(
                value: widget.node.op,
                items: ops.map((o) => DropdownMenuItem(value: o, child: Text(o))).toList(),
                onChanged: (v) {
                  widget.node.op = v ?? widget.node.op;
                  widget.onChanged();
                },
              ),
            ),
          ),
          const SizedBox(width: 6),
          Expanded(
            child: TextField(
              decoration: InputDecoration(
                hintText: 'value',
                contentPadding: const EdgeInsets.symmetric(horizontal: 10, vertical: 8),
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(8), borderSide: BorderSide.none),
                filled: true,
              ),
              controller: rightController,
              onChanged: (v) {
                widget.node.right = v;
                widget.onChanged();
              },
              style: AppTypography.mono.copyWith(fontSize: 12),
            ),
          ),
          const SizedBox(width: 6),
          _SmallToggle(
            label: '"str"',
            active: widget.node.quoted,
            onTap: () {
              widget.node.quoted = !widget.node.quoted;
              widget.onChanged();
            },
          ),
          const SizedBox(width: 4),
          IconButton(
            icon: Icon(Icons.close, size: 16, color: cs.onSurface.withOpacity(0.4)),
            visualDensity: VisualDensity.compact,
            onPressed: () {
              widget.parent.children.remove(widget.node);
              widget.onChanged();
            },
          ),
        ],
      ),
    );
  }
}

// ── Expression tree nodes ─────────────────────────────────────────────────────

abstract class _ExpressionNode {}

class _GroupNode extends _ExpressionNode {
  String op;
  bool negated;
  final List<_ExpressionNode> children;

  _GroupNode({
    required this.op,
    this.negated = false,
    List<_ExpressionNode>? children,
  }) : children = children ?? [];
}

class _ConditionNode extends _ExpressionNode {
  String left;
  String op;
  String right;
  bool quoted;
  bool negated;

  _ConditionNode({
    this.left = '',
    this.op = '==',
    this.right = '',
    this.quoted = false,
    this.negated = false,
  });
}
